# ==========================================
# 1. Configurações do Banco H2 (Em Memória)
# ==========================================
spring.datasource.url=jdbc:h2:mem:eventotechdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# 2. Configurações de E-mail (Obrigatório)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Coloque seu email aqui (ou um fictício só para o Spring rodar)
spring.mail.username=seu_email@gmail.com
# Coloque a senha aqui (ou uma fictícia)
spring.mail.password=123456
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true